replicaCount: 1

mode: "development"

hostname:
  api: "api.abscan.io"
  ui: "abscan.io"

registryCredentials:
  registry: "https://registry.gitlab.com"

imagePullSecrets: "abscan-registry-key"

images:
  api:
    registry: "registry.gitlab.com/alphabravocompany/abscan/replace-me-api-registry"
    tag: "replace-me-api-tag"
  job:
    registry: "registry.gitlab.com/alphabravocompany/dockerfiles/abscan"
    tag: "latest"
  operator:
    registry: "eengelking/abscan-operator"
    tag: "0.1.9"
  rbac:
    registry: "gcr.io/kubebuilder/kube-rbac-proxy"
    tag: "v0.8.0"
  ui:
    registry: "registry.gitlab.com/alphabravocompany/abscan/replace-me-ui-registry"
    tag: "replace-me-ui-tag"
  cveUpdater:
    registry: "registry.gitlab.com/alphabravocompany/abscan/db-updater"
    tag: "latest"
  cveRestore:
    registry: "registry.gitlab.com/alphabravocompany/abscan/db-restore"
    tag: "latest"

persistence:
  enabled: true
  existingClaim: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}
  mountPath: /data

redis:
  host: "redis-master"
  port: "6379"

smtp:
  from:
    name: "ABScan"
    address: "info@mail.ablabs.io"
  service:
    host: "smtp.sparkpostmail.com"
    port: "587"
    username: "SMTP_Injection"
    useTLS: true

cors:
  origins: "http://abscan.io,https://abscan.io,http://abscan.dev,https://abscan.dev"
  methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"

cookie:
  sameSite: "Lax"
  secure: "0"

api:
  logging: "enabled"
  host: "0.0.0.0"

cvesearch:
  workers: "10"
  history:
    successful: 1
    failed: 1
  limits:
    backoff: 3
    deadline: 3600

service:
  api:
    port: "8090"
  ui:
    port: "80"

ingress:
  className: "nginx"
  tls:
    enabled: false