environments:
    default:
        values:
        - "../variables/default/values.yaml"
        secrets:
        - "../variables/default/secrets.yaml"
    production:
        values:
        - "../variables/production/values.yaml"
        secrets:
        - "../variables/production/secrets.yaml"