bases:
- environments.yaml

templates:
  getVars: &getVars
    values:
    - "./charts/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}/values.yaml"
    secrets:
    - "./charts/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}/secrets.yaml"

repositories:
  - name: abscan
    url: https://helm.ablabs.io/abscan
  - name: cve-search
    url: https://helm.ablabs.io/cve-search
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: abscan
    namespace: abscan
    chart: abscan/abscan
    <<: *getVars
  - name: cvesearch
    namespace: abscan
    chart: cve-search/cve-search
    <<: *getVars
  - name: mongodb
    installed: {{ eq .Environment.Name "default" | toYaml }}
    namespace: abscan
    chart: bitnami/mongodb
    <<: *getVars
  - name: redis
    namespace: abscan
    chart: bitnami/redis
    <<: *getVars

helmDefaults:
  atomic: true
  cleanupOnFail: true
  createNamespace: true