bases:
- environments.yaml

templates:
  getVars: &getVars
    values:
    - "./charts/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}/values.yaml"
    secrets:
    - "./charts/{{`{{ .Release.Name }}`}}/{{ .Environment.Name }}/secrets.yaml"

repositories:
  - name: ablabs
    url: https://helm.ablabs.io/abscan
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  # - name: abscan
  #   namespace: abscan
  #   chart: ablabs/abscan
  #   <<: *getVars
  - name: mongodb
    installed: {{ eq .Environment.Name "default" | toYaml }}
    namespace: abscan
    chart: bitnami/mongodb
    <<: *getVars
  - name: redis
    namespace: abscan
    chart: bitnami/redis
    <<: *getVars

helmDefaults:
  atomic: true
  cleanupOnFail: true
  createNamespace: true