registryCredentials:
    password: ENC[AES256_GCM,data:nIKvA2HEZ7+HfMrURuFrbCkCoVcFH10yBec=,iv:RZBDzZxf7S4rG6mbj0oDfzuiHfFYtxRMNCKMVQUlTro=,tag:rsTLvbTKebLESdSRkZ3cJw==,type:str]
    username: ENC[AES256_GCM,data:Q7fElBcCyfWQBw==,iv:GyIJGH+/nHcMNGgcvkii5F7o39rbk02Kuji9otiCt+8=,tag:5o+q1XNAX7POxqhKMx8R5A==,type:str]
    email: ENC[AES256_GCM,data:hubTQ70e52Sdm5nHYKpK,iv:M0pHvFd8+fMMPBvM/j6HSTde9zDeqbELgDhyoncLCHY=,tag:qr15OOFFOtFYAmR+p6znJw==,type:str]
abscan:
    api:
        name: ENC[AES256_GCM,data:nG1R/IiIGmGtSA==,iv:ZhChiU69WTNQW4OQXDfQptpeWw2kiEqYB21ltrccofM=,tag:FmoJQpF0Hb0EsdEB+VXGTA==,type:str]
        variables:
            gitlab:
                projectID: ENC[AES256_GCM,data:RlV9KC+MWy4=,iv:ecAw8pZkDfqa9kG3k+iM4iFoySCL8w9fURfzd4yHRFk=,tag:cTljWAZjl7QHDGvRdbBjPA==,type:int]
                triggerToken: ENC[AES256_GCM,data:gmcA8ueEs9YUolq424lvaVQ/neXlFYpxZokci07B,iv:OfBH/Ahu4OxA+vK3rx+u2ZzShjUumKCThitfpRL7OjI=,tag:Ppa+wDr3VMLwR7UvfkIpAg==,type:str]
                PrivateToken: ENC[AES256_GCM,data:xKJUm9rw8oIOTRn2Uqhf5TDzEtRt9ohwS20=,iv:Es4GAKJ9O4ll5ChA3TzhqzUFbIP49cNeFKvpnO2hpmE=,tag:ZOgT8K8b1PEf0ua3lSDGfg==,type:str]
            database:
                connectionType: ENC[AES256_GCM,data:Tu0i5lkO2Q==,iv:bJfVC2/qgdsJ8utwfDRWgT0QTT8p7EM/53E9wiKaTtQ=,tag:CHnhPEbIAsEU3M77tPK/rA==,type:str]
                host: ENC[AES256_GCM,data:5klz7QEzKQ==,iv:PifyX69hYiM6fYHacjD1ES4q9yB2imc8zOZI1nCSCMo=,tag:bF6x+Rv7zAxJhTgxkDbwyA==,type:str]
                port: ENC[AES256_GCM,data:j8NqtTw=,iv:7VUFljyDUoxf3ric8MXwLDK5Vja2YnkJTtDl7Z1ZTyI=,tag:/pfOemA1xTeFXN5e08IX1g==,type:int]
                user: ENC[AES256_GCM,data:haY02w==,iv:yn8eCLlo9hl9RLHYnZF69PyEnUbzq4CQ7oLd4Iw76nI=,tag:Bwn562kP32IZxBmi0wGEnQ==,type:str]
                pass: ENC[AES256_GCM,data:i6rYSmRu5GASrdjTI8pvYN5Xjl4=,iv:cN7Doqqcpk95OKYF1xBvb4d17vDP86OmLCRlIcIq004=,tag:cpBikmNJvPf6LvdPEHVsEw==,type:str]
            jwt:
                accessTokenSecret: ENC[AES256_GCM,data:unVQhY8q3zdJyqQKAOTf/U8ZmIwX5QMMP2Wnnt3sBNM9fjtm9uwq6IjwOu1miajhX2YxOncNfpI6ToYC,iv:Ag1JfxFUSxlkMqdwxNgZxLX9IUk7sEnbNAcGBks1+mM=,tag:VbESqkdc3vggq2rIMSA7iw==,type:str]
                refreshTokenSecret: ENC[AES256_GCM,data:4V5HZYjmtlqtKvWRT5HmTvcPTULH0iZkGnKOuQe2IdG9kyMcEdEJZ07QzRCKxzOHICHte2tMWeiyykVv,iv:0BgCSJSW9c/GtRJnA8yd78eI0QVo98i/itLZJy2sxIY=,tag:vazWVFER0eZNRv48BjwPpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qeprrxh997g4dkfp34wfh8elkt9366rvavvzjjsvkn8zqd9mqems6udfhh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cVBhS25SSHVUWDc4TUFo
            VnBFZlBFMU56bmVxTDd5SDViYXh1VDBvWFZJCkVMRndxU01DcjdPNTExSlFuTlRr
            NUhEZEgwSUJjZi9RYzlZN2xNTGxWWFkKLS0tIGtCSC9EWnBWV3dMeGpYamRtaEI5
            NjY2VlNYYkNYUDBKeERENnoxQkluTWsKr3F9XfXvlLCR9UViGFG0b/H4maSh6DGs
            JmaHAD6y1SYrUfLV2a8/vpxhaCcLO2ntYR5NiF/jxU+x2Azcir6AHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-24T17:58:32Z"
    mac: ENC[AES256_GCM,data:1J5nXdi5jrc43m66yWGoCZeQNq7RuGqqKwK038ndJel7oTp7SAMPD9PKtMu5zc0v44AifugnJYzwDWuPZ55Piv6og1K9H/8f4ASWNk3goPr199lQfNmZJ4PHjYvf6l5sShlvKu/RM9rzbpDPIvCb4cuqNK73oh484qLWPeM8vbk=,iv:9QKntPeOlaaP9gzKYgMFULFNuaXtH+DpjQ6z6rN3JuM=,tag:7lh++vUFYFjQHtJ5SgtbGA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
